import type { Metadata } from "next";
import "./globals.css";
import { outfit } from "@/fonts";
import Header from "@/components/organisms/Header";
import { cn } from "@/helpers/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(outfit.className, "relative min-h-dvh bg-primary-97")}
      >
        <Header />
        <main className="relative flex flex-col">{children}</main>
        {/* Footer */}
      </body>
    </html>
  );
}
